### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Aeris1One** [HimaJyun/Zabbigot#5]
```
>zabbigot send
> [13:09:36 WARN]: Exception in thread "Craft Scheduler Thread - 44"
> [13:09:36 WARN]: org.apache.commons.lang.UnhandledException: Plugin Zabbigot v1.4.0 generated an exception while executing task 77262
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused (Connection refused)
at jp.jyn.zabbigot.sender.imple.ZabbixSender.send(ZabbixSender.java:60)
at jp.jyn.zabbigot.StatusManager.send(StatusManager.java:71)
at jp.jyn.zabbigot.command.sub.Send.lambda$onCommand$0(Send.java:22)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:607)
at jp.jyn.zabbigot.sender.imple.ZabbixSender.send(ZabbixSender.java:38)
... 8 more
```

Config is using the right IP and right port and I already have a zabbix agent on the server hosting spigot which works well with same IP and port

**Comment by HimaJyun** [comment]
Hi, I checked your issue.

I need more info. Try this list.

- Java version (run `java -version` command)
- Spigot version (run `/version` command in game)
- Zabbix version (run `sudo zabbix_server -V` command in zabbix server)
- Try using `127.0.0.1` and `::1` as zabbix server address (If zabbix server and Spigot server on the same machine.)
- Run `netstat -atn` command in zabbix server.

If the problem persists, please attach the config.yml.
