### ISSUE TITLE
1.17 issue

### ISSUE THREAD

**Issue by deltaflyer4747** [HimaJyun/Zabbigot#6]
Hi, i know this is 2y since last update, but ... man can hope, right? :) Having this issue with new spigot, is there anything you can do? Thanks in advance...

java ver:        openjdk version "16.0.2" 2021-07-20
spigot ver:    1.17.1
zabb ver:      5.4.3

[17:02:02 WARN]: [Zabbigot] Plugin Zabbigot v1.4.0 generated an exception while executing task 1893
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-296]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2287) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:968) ~[patched_1.17.1.jar:git-Paper-296]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:379) ~[patched_1.17.1.jar:git-Paper-296]
        at jp.jyn.zabbigot.EventCounter.lambda$new$14(EventCounter.java:103) ~[Zabbigot-1.4.0.jar:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at jp.jyn.zabbigot.EventCounter.lambda$new$15(EventCounter.java:103) ~[Zabbigot-1.4.0.jar:?]
        at jp.jyn.zabbigot.sender.imple.ZabbixSender.toJson(ZabbixSender.java:105) ~[Zabbigot-1.4.0.jar:?]
        at jp.jyn.zabbigot.sender.imple.ZabbixSender.send(ZabbixSender.java:34) ~[Zabbigot-1.4.0.jar:?]
        at jp.jyn.zabbigot.StatusManager.send(StatusManager.java:71) ~[Zabbigot-1.4.0.jar:?]
        at jp.jyn.zabbigot.command.sub.Send.lambda$onCommand$0(Send.java:22) ~[Zabbigot-1.4.0.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-296]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-296]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-296]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by HimaJyun** [comment]
Oops, I fixed this bug. Please try new version.([1.4.1](https://github.com/HimaJyun/Zabbigot/releases/tag/v1.4.1))
Thanks your report!!

**Comment by deltaflyer4747** [comment]
Looks fine on my and, thank you very much for this quick response! Much appreciated :)
